services:
  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.2



  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    ports:
      - "6380:6380"
    volumes:
      - ./config/redis2.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.3

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    ports:
      - "6381:6381"
    volumes:
      - ./config/redis3.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.4


  redis-node-4:
    image: redis:7
    container_name: redis-node-4
    ports:
      - "6382:6382"
    volumes:
      - ./config/redis4.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.5

  redis-node-5:
    image: redis:7
    container_name: redis-node-5
    ports:
      - "6383:6383"
    volumes:
      - ./config/redis5.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.6

  redis-node-6:
    image: redis:7
    container_name: redis-node-6
    ports:
      - "6384:6384"
    volumes:
      - ./config/redis6.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      redis-cluster-network:
        ipv4_address: 172.28.0.7

  redis-insight:

    # network_mode: "service:redis-cluster"
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
      - 5540:5540

#
#  redis-cluster:
#    image: redis:7
#    container_name: redis-cluster
#    ports:
#      - "6385:6385"
#    volumes:
#      - ./config/redis.conf:/etc/redis/redis.conf
#    command: >
#      sh -c "
#        sleep 10;
#        yes yes | redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379  --cluster-yes && redis-cli --cluster add-node redis-node-4:6379 redis-node-1:6379 --cluster-slave && redis-cli --cluster add-node redis-node-5:6379 redis-node-2:6379 --cluster-slave && redis-cli --cluster add-node redis-node-6:6379 redis-node-3:6379 --cluster-slave
#      "
#    depends_on:
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-5
#      - redis-node-6

networks:
  redis-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16




#redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381



